### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'column'                                                                                                  │

### ISSUE THREAD

**Issue by yingzhu146** [joouha/euporie#15]
Apologies for opening so many issues!

Just ran into an issue with completion. I can reproduce this error reliably when using tab-completion on this locally installed package (`pip install -e .`). As soon as I press the tab key, I get the following (`from priv_lib.che` is the private library, I pressed tab after the `che`)

```shell

                                        │ ╭───┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │
                                        │ │[ ]│ 1 from priv_lib.che[IPKernelApp] ERROR | Exception in message handler:                                           │ │
Traceback (most recent call last):      │ ╰───┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
  File "/Users/yingzhu_/miniconda3/envs/python38/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell                                 │
    yield gen.maybe_future(handler(stream, idents, msg))                                                                                                           │
  File "/Users/yingzhu_/miniconda3/envs/python38/lib/python3.8/site-packages/tornado/gen.py", line 762, in run                                                     │
    value = future.result()             │                                                                                                                          │
  File "/Users/yingzhu_/miniconda3/envs/python38/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper                                                 │
    yielded = ctx_run(next, result)     │                                                                                                                          │
  File "/Users/yingzhu_/miniconda3/envs/python38/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 576, in complete_request                               │
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))                                                                                           │
  File "/Users/yingzhu_/miniconda3/envs/python38/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 356, in do_complete                                      │
    return self._experimental_do_complete(code, cursor_pos)                                                                                                        │
  File "/Users/yingzhu_/miniconda3/envs/python38/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete                        │
    completions = list(_rectify_completions(code, raw_completions))                                                                                                │
  File "/Users/yingzhu_/miniconda3/envs/python38/lib/python3.8/site-packages/IPython/core/completer.py", line 484, in rectify_completions                          │
    completions = list(completions)     │                                                                                                                          │
  File "/Users/yingzhu_/miniconda3/envs/python38/lib/python3.8/site-packages/IPython/core/completer.py", line 1818, in completions                                 │
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):                                                                        │
  File "/Users/yingzhu_/miniconda3/envs/python38/lib/python3.8/site-packages/IPython/core/completer.py", line 1861, in _completions                                │
    matched_text, matches, matches_origin, jedi_matches = self._complete(                                                                                          │
  File "/Users/yingzhu_/miniconda3/envs/python38/lib/python3.8/site-packages/IPython/core/completer.py", line 2029, in _complete                                   │
    completions = self._jedi_matches(   │                                                                                                                          │
  File "/Users/yingzhu_/miniconda3/envs/python38/lib/python3.8/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches                               │
    interpreter = jedi.Interpreter(     │                                                                                                                          │
  File "/Users/yingzhu_/miniconda3/envs/python38/lib/python3.8/site-packages/jedi/api/__init__.py", line 725, in __init__                                          │
    super().__init__(code, environment=environment,                                                                                                                │
TypeError: __init__() got an unexpected keyword argument 'column'                                                                                                  │
                                        │                                                                                                                          │

```

**Comment by joouha** [comment]
I'm guessing this is a bug somewhere between your `priv_lib` package and `jedi` / `IPython`.

**Comment by yingzhu146** [comment]
Yeah - can repro issue in jupyter lab too - reinstall of jedi solved. thank you!
